### ISSUE TITLE
[Testing Party] Automatically signed out after adding a new business

### ISSUE THREAD

**Issue by spicysos** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#127]
I logged in using test5@nyu.edu and filled out the form for creating a new business. Then, the page signs me out automatically and shows this page below. (screenshot) I think this bug might be related to the validation of the new business form because I typed an invalid phone number (e.g. 1-12345) and tried submitting it.

![image](https://user-images.githubusercontent.com/48112292/231834573-ab4063cf-a0c7-41d9-a33e-e20c00620c0f.png)

**Comment by vchrombie** [comment]
> I logged in using [test5@nyu.edu](mailto:test5@nyu.edu) and filled out the form for creating a new business. Then, the page signs me out automatically and shows this page below. (screenshot) I think this bug might be related to the validation of the new business form because I typed an invalid phone number (e.g. 1-12345) and tried submitting it.

Hi @spicysos, thanks for opening the issue. The issue was with the AWS instance as mentioned in the document.

> If you encounter unusual behavior with the AWS instance, we kindly ask for your patience. Please wait for a few minutes before performing any actions again.

We tried adding a business and we were able to get it right using the same details which you mentioned.

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/25265451/232166610-931c3e67-9c80-4ad9-b348-d1071d99b1f5.png">
